name: single-stage-ui
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - uat
      - prod
    paths:
      - frontend/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
      with:
        sparse-checkout: frontend
        sparse-checkout-cone-mode: true
    - uses: Azure/login@v2.0.0
      with:
        creds: ${{SECRETS.AZURE_SERVICE_PRINCIPAL_CRED}}
        auth-type: SERVICE_PRINCIPAL
    - run: |
        cd frontend
    - uses: actions/setup-node@v4.0.3
      with:
        node-version: v20.17.0
    - run: |
        npm install
    - run: |
        npm run build
    - run:
        zip -rv  build.zip ./build/**
    - run: |
        az webapp config appsettings set --resource-group ${{vars.RESOURCE_GROUP_NAME}} --name "${{vars.APP_SERVICE_UI_NAME}}" --settings SCM_DO_BUILD_DURING_DEPLOYMENT=false
    - run: |
        az webapp deploy --name ${{vars.APP_SERVICE_UI_NAME}} --resource-group  ${{vars.RESOURCE_GROUP_NAME}} --src-path ./build.zip --type zip
    - run: |
        az webapp log config --web-server-logging filesystem --name ${{vars.APP_SERVICE_UI_NAME}} --resource-group  ${{vars.RESOURCE_GROUP_NAME}}
